AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - '.bundle/**/*'
    - 'vendor/bundle/**/*'
    - 'bin/spring'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'test/test_helper.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - !ruby/regexp /old_and_unused\.rb$/

Rails:
  Enabled: true
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
